[package]
name = "server"
version = "0.1.0"
authors = ["Jeff Lai <winfield301@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.2"
dotenv = "0.15.0"
tokio-postgres = "0.5.1"
tokio = { version = "0.2", features = ["macros"] }
handlebars = "3.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
