[package]
name = "server"
version = "0.1.0"
authors = ["Jeff Lai <winfield301@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
actix = "0.9.0"
futures = "0.3.1"
askama = "0.8"
bytes = "0.5.3"
serde = "1"
ring = "0.16.9"
hex = "0.4.0"
dotenv = "0.15.0"
tokio-postgres = "0.5.1"
deadpool-postgres = "0.4.3"
