[package]
name = "server"
version = "0.1.0"
authors = ["Jeff Lai <winfield301@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
askama = "0.8"
tokio-postgres = "0.3.0"
serde = "1"
ring = "0.16.9"
hex = "0.4.0"
